version: '3'
services:
  mqtt:
    image: tonyapuzzo/rpi-mosquitto
    volumes:
      - /home/pi/home-assistant/mosquitto/config:/mosquitto/config
      - /home/pi/home-assistant/mosquitto/data:/mosquitto/data
    networks:
      - outside
    
  hass:
    image: tonyapuzzo/rpi-home-assistant:beta
    #image: tonyapuzzo/rpi-home-assistant:latest
    volumes:
      - /home/pi/home-assistant/configuration:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - outside

networks:
  outside:
    external:
      name: "host"

# vim: sw=2 ts=2 expandtab ai
